### ISSUE TITLE
Latest transactions above X price now fails to resolve

### ISSUE THREAD

**Issue by Anaglyph-ic** [teztok/indexer#65]
I'm trying to pass the following request to the API (https://graphiql.teztok.com/).

```graphql
query latestGeneralTransactions {
      events(
        limit: 500
        order_by: { opid: desc }
        where: {
          token: { metadata_status: { _eq: "processed" } }
          implements: { _eq: "SALE" }
          price_in_usd: { _gte: "100000000" }
        }
      ) {
        type
        timestamp
        seller_address
        buyer_address
        price

        implements
        level
        price_in_usd
        token_id
        id
        fa2_address
        token {
          fa2_address
          token_id
          editions
          name
          mime_type
          description
          price
          platform
          last_sale_at
          display_uri
          artifact_uri
          last_sales_price
          artist_profile {
            account
            alias
            twitter
          }
        }

        seller_profile {
          alias
        }

        buyer_profile {
          account
          alias
        }
      }
    }
  ```

After trying to process it, it yields the following error:

```
TypeError: Failed to fetch
    at b (https://graphiql.teztok.com/static/js/main.e9bbb139.chunk.js:1:1275)
    at n.value (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:593902)
    at push.j.handleRunQuery [as onRun] (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:595962)
    at push.t.ExecuteButton.n._onClick (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:603673)
    at Object.<anonymous> (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:481058)
    at p (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:481096)
    at https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:481734
    at _ (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:481823)
    at x (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:482259)
    at S (https://graphiql.teztok.com/static/js/1.dac19ace.chunk.js:1:482071)
```

**Comment by xat** [comment]
I had a quick look: The query was quite complex and resulted in a timeout. I added an index `price_in_usd` column, it now completes within a few seconds.

**Comment by Anaglyph-ic** [comment]
It now works and has much better performance. Thank you for this!
